server:
  port: 9004

logging:
  level:
    org.springframework.security.oauth2: debug

spring:
  application:
    name: zhys-gateway
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      profile: ${spring.profiles.active}
      label: master
      discovery:
        service-id: zhys-config
        enabled: true
#  zipkin:
#    enabled: false

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://zhys-registry:9000/eureka
